import type { Metadata } from 'next';
import { LegalPageShell, type LegalSection } from '@/components/LegalPageShell';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Read how Alpha Legal Intake collects, uses, shares, and protects information submitted through our legal intake services website.',
};

const sections: LegalSection[] = [
  { title: 'Scope and Purpose', paragraphs: ['This Privacy Policy describes how Alpha Legal Intake collects, uses, discloses, and safeguards information when you visit our website, request intake support, communicate with our team, or interact with services made available through this platform.', 'Alpha Legal Intake operates as a legal intake, accident call center, and lead generation service provider. We are not a law firm and do not provide legal advice.', 'By using this website or submitting information to Alpha Legal Intake, you acknowledge the practices described in this Privacy Policy as of the effective date listed on this page.'] },
  { title: 'Information We Collect', paragraphs: ['We collect information you voluntarily provide when you complete an intake request, contact form, call request, or similar experience. This may include your name, telephone number, email address, ZIP code, accident details, injury indicators, representation status, and other details you choose to provide.', 'We may also collect operational data associated with a submission, including consent records, timestamps, lead-identification tokens, page URLs, and communication preferences.'], bullets: ['Device and usage information such as browser type, IP address, referring page, pages visited, session timing, and analytics data.', 'Cookies, pixels, and similar technologies used to understand site performance, improve usability, and measure campaign effectiveness.', 'Communications you send to Alpha Legal Intake by email, phone, text, or web form, including follow-up questions and support requests.'] },
  { title: 'How We Use Information', paragraphs: ['Alpha Legal Intake uses collected information to respond to intake requests, verify accident details, qualify potential personal injury opportunities, coordinate live transfer calls, operate the website, improve our user experience, and maintain internal records.', 'We may use your information to personalize outreach, document consent, prevent fraud, troubleshoot technical issues, comply with legal obligations, and communicate important service or policy updates.', 'Where permitted by law and based on your preferences, we may also use your information to send relevant communications about Motor Vehicle Accident leads, legal intake services, and accident call center support.'] },
  { title: 'How Information May Be Shared', paragraphs: ['We do not sell your personal information for cash consideration. We may disclose information to participating law firms, legal marketing partners, call center partners, CRM and hosting providers, analytics vendors, and service providers that support intake workflows or website operations.', 'Information may also be disclosed when reasonably necessary to protect the rights, safety, or property of Alpha Legal Intake, our users, or others; to investigate suspected fraud or abuse; to enforce our terms; or to comply with subpoenas, court orders, legal process, or lawful requests.', 'If Alpha Legal Intake is involved in a merger, acquisition, financing, or sale of assets, information may be transferred as part of that transaction subject to appropriate confidentiality and legal safeguards.'] },
  { title: 'Consent and Communications', paragraphs: ['When you submit an intake request, you may authorize Alpha Legal Intake and its participating legal marketing or attorney partners to contact you by phone, text message, or email regarding accident intake, personal injury lead qualification, live transfer coordination, and related legal services.', 'Your consent to receive communications is not a condition of purchase. Message and data rates may apply to text communications. You may opt out of marketing communications using the instructions provided in the communication or by contacting us directly.', 'Alpha Legal Intake is not a law firm, does not provide legal advice, and does not guarantee case acceptance or any legal outcome.'] },
  { title: 'Cookies and Analytics', paragraphs: ['We and our service providers may use cookies, local storage, tags, and similar technologies to maintain site functionality, remember preferences, attribute marketing activity, and understand how users interact with the website.', 'Most browsers allow you to block or delete cookies. Disabling certain technologies may affect the availability or functionality of some features on the site.'] },
  { title: 'Data Security and Retention', paragraphs: ['Alpha Legal Intake uses administrative, technical, and physical safeguards designed to protect information against unauthorized access, disclosure, alteration, or destruction.', 'No internet transmission or storage system can be guaranteed to be completely secure. We retain information for as long as reasonably necessary to provide services, document compliance, resolve disputes, enforce agreements, and satisfy legal, operational, or recordkeeping obligations.'] },
  { title: 'Your Choices and Privacy Rights', paragraphs: ['You may choose not to provide information through our forms, but some services or response workflows may not be available without the requested details.', 'Residents of certain states may have additional rights regarding access, deletion, correction, or opt-out requests. We will review and respond to eligible requests in accordance with applicable law and may need to verify your identity before fulfilling a request.'] },
];

export default function PrivacyPolicyPage() {
  return <LegalPageShell eyebrow="Privacy and Data Use" title="Privacy Policy" intro="Alpha Legal Intake is committed to handling personal information with clarity, restraint, and a professional standard of trust for legal intake and accident lead generation workflows." effectiveDate="May 13, 2026" documentLabel="Website Privacy Policy" sections={sections} />;
}
