import type { Metadata } from 'next';
import { LegalPageShell, type LegalSection } from '@/components/LegalPageShell';

export const metadata: Metadata = { title: 'Terms & Conditions', description: 'Review the terms governing use of the Alpha Legal Intake website and legal intake request experience.' };

const sections: LegalSection[] = [
  { title: 'Agreement to Terms', paragraphs: ['These Terms & Conditions govern your access to and use of the Alpha Legal Intake website, intake request forms, informational content, and related digital services.', 'By using the website, submitting information, or contacting us through the platform, you agree to these terms and all applicable laws.'] },
  { title: 'Services and Role', paragraphs: ['Alpha Legal Intake is a legal intake, accident call center, and lead generation service provider for personal injury law firms and legal marketing teams.', 'Alpha Legal Intake is not a law firm, does not provide legal advice, and does not create an attorney-client relationship. Any attorney-client relationship can only be formed by a law firm under its own procedures.'] },
  { title: 'No Guarantee', paragraphs: ['Submitting a request through this website does not guarantee that a law firm will accept a matter, contact a caller, provide representation, or achieve any result.', 'Lead availability, live transfer volume, qualification outcomes, and campaign performance vary by market, timing, criteria, and operational factors.'] },
  { title: 'Communications Consent', paragraphs: ['If you provide contact information, Alpha Legal Intake and its participating legal marketing or attorney partners may contact you by phone, text message, or email regarding accident intake, personal injury lead qualification, live transfer coordination, and related legal services.', 'Your consent to receive communications is not a condition of purchase, and you may revoke consent as permitted by law.'] },
  { title: 'Informational Content', paragraphs: ['Content on this website is provided for general informational purposes only. It is not legal advice, tax advice, financial advice, or a substitute for consultation with a qualified attorney.', 'While Alpha Legal Intake strives to keep website content current and accurate, we do not warrant that content is complete, error-free, or suitable for every situation.'] },
  { title: 'Acceptable Use', paragraphs: ['You agree not to misuse the website, submit false or misleading information, interfere with site operations, attempt unauthorized access, or use the platform for unlawful purposes.', 'If Alpha Legal Intake reasonably believes a submission is fraudulent, abusive, or unlawful, we may decline to process it and may take protective or legal action where appropriate.'] },
  { title: 'Intellectual Property', paragraphs: ['All website content, branding, design elements, text, graphics, software, and other materials made available by Alpha Legal Intake are protected by applicable intellectual property laws and remain the property of Alpha Legal Intake or its licensors.', 'You may view and use the website for personal, non-commercial purposes only unless Alpha Legal Intake provides prior written permission for another use.'] },
  { title: 'Changes to Terms', paragraphs: ['Alpha Legal Intake may revise these Terms & Conditions from time to time. Updated terms become effective when posted on this page unless a later effective date is stated.', 'Your continued use of the website after changes are posted means you accept the updated terms.'] },
];

export default function TermsOfServicePage() {
  return <LegalPageShell eyebrow="Website Terms" title="Terms & Conditions" intro="These terms define how the Alpha Legal Intake website may be used and set the framework for legal intake requests, accident call center support, and communication workflows offered through this platform." effectiveDate="May 13, 2026" documentLabel="Terms & Conditions" sections={sections} />;
}
